title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.gaurang
      - entity: person.khushboo
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - remote.harmony_hub
        title: Living Room
      - type: weather-forecast
        entity: weather.home

